### ISSUE TITLE
How to add options to URL

### ISSUE THREAD

**Issue by songtaogui** [vgteam/sequenceTubeMap#85] opened 2019-12-18 08:50 UTC
Hi,

I have tried sequenceTubeMap on my local sever and it works great.

However, I would like to link certain regions from other webpage to the visualization on sequenceTubeMap. So is it practicable to add some URL parameters such as "data","path name","start" and "length" that automaticly leading to the graphic view of the designated region ?

Which scripts should I refer to, if I would like add URL parameters in my local version of sequenceTubeMap?

Thank you

Any suggestion would be grateful.

Best wishes,

Songtao Gui

**Comment by adamnovak** [comment] 2021-03-05 00:40
We don't currently have a way to determine the initial view from URL parameters or a hashbang, but there's no reason we couldn't do that.

A potential workaround is depending on the repo and using the `TubeMapContainer` in an enclosing React application that does direct it to display the region of interest.

**Comment by adamnovak** [comment] 2022-02-17 23:14
This is actually a duplicate of #37 I think; we want to be able to have a URL that points to a view.

**Closed by adamnovak** 2022-02-17 23:14 UTC
