### ISSUE TITLE
vg view failed:

### ISSUE THREAD

**Issue by Overcraft90** [vgteam/sequenceTubeMap#176] opened 2022-08-13 02:21 UTC
Hi there,

I just installed **_vg_** following the `Build on Linux` instructions. Afterwards, I tried to visualize my own data using **_sequenceTubeMap_**; unfortunately, for some reason I got an error on the web page saying: "vg view failed:".

At first I thought it could have been my pangenome, which I generated with **_minigraph-CACTUS_**, but actually this happens also for the examples provided with the tool... I followed the points indicated for `Adding your own data` to index my .vg file, and to set my "data Path" to the directory where all the original files are stored. 

Despite doing this, the error seems to stem from something else I'm not aware of. Moreover, with my directory set I tried to use the `custom (mounted files)` but the drop-down menus showed no options to select from. One last thing, I noticed that when launching with `yarn serve` I got a link to a webpage: [http://[::]:3000](url) that it is not the [localhost:3001](url) indicated on the Git repository.

Could this be the reason why _**sTM**_ is not working? Let me know, thanks in advance!

**Comment by adamnovak** [comment] 2022-08-16 20:18
I think we worked this out today; the missing files were #177 which was fixed in #178. After that we hit https://github.com/vgteam/vg/issues/3716 which is worked around by using the static release vg binaries. I've opened an issue for the confusing URLs as #179; the discrepancy there isn't the root cause of any of the other issues.

**Closed by adamnovak** 2022-08-16 20:18 UTC
